// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwMDkUQHl-bQ39lUqKH1st6PReSfrN-DQ',
    appId: '1:1038376559274:web:5ba14c2532930f436026d3',
    messagingSenderId: '1038376559274',
    projectId: 'connect-me-community-app',
    authDomain: 'connect-me-community-app.firebaseapp.com',
    storageBucket: 'connect-me-community-app.firebasestorage.app',
    measurementId: 'G-6M39PYTJBZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1d5JEgy-ZAAqbtbPrCPTJZtkm5sP4mJ8',
    appId: '1:1038376559274:android:4749d42b2c96d8276026d3',
    messagingSenderId: '1038376559274',
    projectId: 'connect-me-community-app',
    storageBucket: 'connect-me-community-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2YEx6ZsCk3lpguqeDHKAf86bnNJx4lO0',
    appId: '1:1038376559274:ios:18d768b71eddf4816026d3',
    messagingSenderId: '1038376559274',
    projectId: 'connect-me-community-app',
    storageBucket: 'connect-me-community-app.firebasestorage.app',
    iosBundleId: 'com.example.connectmeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2YEx6ZsCk3lpguqeDHKAf86bnNJx4lO0',
    appId: '1:1038376559274:ios:18d768b71eddf4816026d3',
    messagingSenderId: '1038376559274',
    projectId: 'connect-me-community-app',
    storageBucket: 'connect-me-community-app.firebasestorage.app',
    iosBundleId: 'com.example.connectmeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwMDkUQHl-bQ39lUqKH1st6PReSfrN-DQ',
    appId: '1:1038376559274:web:117003601638c9076026d3',
    messagingSenderId: '1038376559274',
    projectId: 'connect-me-community-app',
    authDomain: 'connect-me-community-app.firebaseapp.com',
    storageBucket: 'connect-me-community-app.firebasestorage.app',
    measurementId: 'G-X677831M5D',
  );
}
